/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: fallenffgrave (https://sketchfab.com/fallenffgrave)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/objb7-191f0d24581248fcbd5adbf63cbeafd3
title: Objb7
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    objb7: THREE.MeshBasicMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.81, -0.64]} rotation={[-1.97, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.objb7} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
