/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: fallenffgrave (https://sketchfab.com/fallenffgrave)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/00e6e812fdbb4733bf1ed8eb8b29934e
title: Татьяна
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    obj11: THREE.MeshBasicMaterial
  }
}

export default function WomanModel({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes } = useGLTF('/woman.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.49, 5.32, -1.99]} rotation={[-2.38, -0.07, -0.07]}>
        <mesh geometry={nodes.Object_2.geometry} material={nodes.Object_2.material} />
        <mesh geometry={nodes.Object_3.geometry} material={nodes.Object_3.material} />
        <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
        <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/woman.gltf')
