/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: fallenffgrave (https://sketchfab.com/fallenffgrave)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/objn3-22736d441ea94585b9c3ade428255472
title: Objn3
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    objn3: THREE.MeshBasicMaterial
  }
}

export default function YoungWomanModel({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/youngwoman.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.1, -2.69, -0.12]} rotation={[-1.18, 0.07, -0.03]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.objn3} />
      </group>
    </group>
  )
}

useGLTF.preload('/youngwoman.gltf')
